# Generated by Django 5.2.15 on 2026-06-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_academic_year_period_lesson_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='default_period_duration',
            field=models.PositiveIntegerField(default=45),
        ),
    ]
