# Generated by Django 5.2.16 on 2026-07-17 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_academicyear_default_period_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='planned_substitute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_substitutions', related_query_name='planned_substitution', to='app.teacher'),
        ),
    ]
