# Generated by Django 5.2.16 on 2026-09-17 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_backfill_academicyear_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['school', '-name']},
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='app.school'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_academic_year_name_per_school'),
        ),
    ]
